services:
  nilabiru-portainer-agent:
    image: portainer/agent:latest
    container_name: nilabiru-portainer-agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - nilabiru-data-hub-agent

  nilabiru-tailscale:
    image: tailscale/tailscale:latest
    container_name: nilabiru-tailscale
    restart: always
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_HOSTNAME=${TS_HOSTNAME}
    volumes:
      - tailscale-data:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
    network_mode: host

volumes:
  tailscale-data:

networks:
  nilabiru-data-hub-agent:
    driver: bridge
