name: Run Github Runners CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Validate Docker Compose
        run: docker compose config --quiet

      - name: Run Deploy Script
        run: docker compose up -d --remove-orphans
